name: Render documents with rmarkdown-action

runs-on:
  workflow_dispatch:
  push:    
    branches:
      - main
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: licencing_income.Rmd
	        output_format: html_document
          output_file: build/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
