name: Render documents with rmarkdown-action

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install curl
        run: |
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up tinytex
        uses: r-lib/actions/setup-tinytex@v2
      
      - name: Set up Renv
        uses: r-lib/actions/setup-renv@v2

      - name: Make build folders
        run: |
          mkdir build

      - name: Render document
        run: |
          Rscript build.R

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
