name: Render documents with rmarkdown-action

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    container: rocker/r-base
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Make build folders
        run: |
          mkdir build

      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: licencing_income.Rmd
          output_format: html_document

      - name: Rename and move output input_file
        run: |
          mv licencing_income.html build/index.html

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
